### ISSUE TITLE
Problems with SAML-COS in intersystems-ib

### ISSUE THREAD

**Issue by rcemper** [PYDuquesnoy/SAML-COS#2]
Hi Piere,
Your code went to intersystems-ib/.. repository
yesterday David González Buisán changed some code ignoring my pending PullRequest
he did a half fix of the  license issue (The **latest** instead of a version that is already superseded now)
and in addition, the port of the superserver (1972 since about half a year) is still wrong.
In addition, issues are disabled which causes conflict in OpenExchange.

Therefore I send this issue to you.
It might be necessary to train him on the handling of Github.

I hope you are personal well.
Best regards from Vienna, Robert

**Comment by PYDuquesnoy** [comment]
Hello Robert,
I did not see this message until today...I see it has been fixed by now.
